name: PHP_CodeSniffer

on: pull_request

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!

      - name: Set PHPCS version
        run: composer require "squizlabs/php_codesniffer=*"

      - name: Run PHPCS
        run: composer run-script phpcs
