name: PHP_Code_Sniffer
on: pull_request
jobs:
  PHPCS_Inspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run PHPCS inspection
        uses: rtCamp/action-phpcs-code-review@v2
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          SKIP_FOLDERS: "tests,.github,vendor,storage,config,bootstrap"
          PHPCS_SNIFFS_EXCLUDE: "WordPress.Files.FileName"
        with:
          args: "PSR2,PSR12"
